[[redirects]]
  from = "/blog/*"
  to = "https://goauthentik.io/blog/:splat"

# Migration from docs to separate directory
[[redirects]]
  from = "/docs/integrations/*"
  to = "/integrations/:splat"

# Docusaurus update removes index
[[redirects]]
  from = "/docs/:firstPart/index"
  to = "/docs/:firstPart/"
  status = 301
  force = true
[[redirects]]
  from = "/docs/:firstPart/:secondPart/index"
  to = "/docs/:firstPart/:secondPart/"
  status = 301
  force = true
[[redirects]]
  from = "/integrations/:firstPart/index"
  to = "/integrations/:firstPart/"
  status = 301
  force = true
[[redirects]]
  from = "/integrations/:firstPart/:secondPart/index"
  to = "/integrations/:firstPart/:secondPart/"
  status = 301
  force = true

# Migrate API and blueprints into main docs
[[redirects]]
  from = "/developer-docs/api*"
  to = "/docs/api:splat"
[[redirects]]
  from = "/developer-docs/blueprints*"
  to = "/docs/blueprints:splat"
# Migrate base source docs into main section
[[redirects]]
  from = "/integrations/sources*"
  to = "/docs/sources:splat"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

[dev]
  command = "npm run watch"
  targetPort = 3000
  publish = "build"

# Moving doc files
[[redirects]]
  from = "/docs/core/applications"
  to = "/docs/applications"
  status = 302
